#!/usr/bin/env python3.3

# ---------------------------------------------------------------------------
#
# minty, a tiny manuscript tool
#
# ---------------------------------------------------------------------------
"""
Copyright (c) 2016, David H. Rogers 
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
# ---------------------------------------------------------------------------



newfile = "test.rtf"

FONT = {
    "size"   : "24",
    "family" : "Courier"
}

MARGIN = {
    "t" : "1440",
    "b" : "1440",
    "l" : "1440",
    "r" : "1440"
}

SPACING = {
    "paragraph" : "480", # Does this work?
    "parindent" : "720",
    "newchapb"  : "3600",
    "newchapa"  : "360",
    "chapsuba"  : "720",
    "titleskip" : "3600"
}

TEST_SCENE = "Urbem Romam a principio reges habuere; libertatem etconsulatum L. Brutus instituit. dictaturae ad tempussumebantur; neque decemviralis potestas ultra biennium,neque tribunorum militum consulare ius diu valuit. Non Cinnae, non Sullae longa dominatio; et Pompei Crassique potentia cito in  Caesarem, Lepidi atque Antonii arma in Augustum cessere, qui cuncta discordiis civilibus fessa nomine principis sub imperium accepit."

# -----------------------------------------------------------------------------
# write document preamble
# -----------------------------------------------------------------------------
def write_preamble( f ):
    f.write("""{{\\rtf1 \\titlepg \\ansi \\margt{0} \\margb{1} \\margl{2}
    \\margr{3} \\pgnrestart \\pgnstarts0
{{\\fonttbl {{\\f0 \\fmodern \\fcharset0 {4};}}}}
\n""".format(MARGIN["t"], MARGIN["b"], MARGIN["l"], MARGIN["r"],
             FONT["family"]))

# -----------------------------------------------------------------------------
# write the common headers on all pages
# -----------------------------------------------------------------------------
def write_headers( f, author, manuscript ):
    f.write("{\\headerf \\pard \\qr \\par}\n")
    f.write("{{\\header \\pard \\qr {0} / {1} / \\chpgn \\par}}\n".format(author["surname"], manuscript["running title"].upper()))

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_wordcount( f, numwords ):
    f.write("""
\\pard \\f0 \\fs{0} \\qr
approx. {1} words
\\par
\n""".format(FONT["size"], str(numwords)))

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_author( f, author ):
    f.write("""
\\pard \\f0 \\fs{0} \\ql
{1} \\
{2} \\
{3}, {4} {5} \\
{6} \\
{7}
\\par
\n""".format(FONT["size"], author["name"], author["address"], author["city"], author["state"],
author["zip"], author["email"], author["phone"]))

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_title(f, title, author):
    f.write("""
\\pard \\f0 \\fs{0} \\sl{1} \\slmulti1 \\sb{2} \\qc {3} \\par
\\pard \\f0 \\fs{4} \\sl{5} \\slmulti1 \\qc by \\
{6}\\
\par\n""".format(FONT["size"], SPACING["paragraph"], SPACING["titleskip"], title, FONT["size"],
SPACING["paragraph"], author["name"]))

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_postamble(f):
    f.write("\n}\n")

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_chapter_heading(f, chapter):
    f.write("""
\\pard \\pagebb \\f0 \\fs{0} \\sl{1} \\slmulti1 \\qc \\sb{2} \\sa{3} {{\\b {4} }}
\\par
\\pard \\f0 \\fs{5} \\sl{6} \\slmulti1 \\qc \\sa{7} {{\\b {8} }}
\par\n""".format(FONT["size"], SPACING["paragraph"], SPACING["newchapb"],
SPACING["newchapa"], chapter["title"], FONT["size"], SPACING["paragraph"],
SPACING["chapsuba"], chapter["subtitle"]))

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_chapter(f, chapter):
    write_chapter_heading(f, chapter)
    write_scene(f)
    write_scene_separator(f)
    write_scene(f)
    write_scene_separator(f)
    write_scene(f)

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_scene(f):
    f.write("""
\\pard \\fi{0} \\sl{1} \\slmult1 \\f0 \\fs{2}
{3}
\\par""".format(SPACING["parindent"], SPACING["paragraph"], FONT["size"], TEST_SCENE))

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
#TODO: add SPACING, etc. in this 
def write_scene_separator(f):
    f.write("\n\\pard \\sl480 \\slmulti1 \\qc \\sa720 ### \\par\n")

# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
def write_chapters(f):
    chapter = {
        "title" : "This is the title",
        "subtitle" : "This is the subtitle"
    }
    write_chapter(f, chapter)

# temporary values
numwords = 2700
font = "Courier"
margin = [ "1440", "1440", "1440", "1440" ]
author = {
	"name"      : "David H. Rogers",
    "surname"   : "Rogers",
    "address"   : "1716 Camino Uva",
    "city"      : "Los Alamos",
    "state"     : "NM",
    "zip"       : "87544",
    "email"     : "david@dhrogers.com",
    "phone"     : "(505) 259-7557"
}
manuscript = {
    "running title" : "Spook"
}
title = "This is The Book"

# -----------------------------------------------------------------------------
#
# execute
#
# -----------------------------------------------------------------------------
with open( newfile, "w" ) as f:
    write_preamble(f)
    write_headers(f, author, manuscript)
    write_wordcount(f, numwords)
    write_author(f, author)
    write_title(f, title, author)
    write_chapters(f)
    write_chapters(f)
    write_postamble(f)


