#!/usr/bin/env python3

from collections import Counter
import sys

if (len(sys.argv) == 1):
    print("ERROR: must include the name of the file to count")

ignore = ["a", "an", "and", "are", "but", "by", "in", "from", "of", "on", "or", "the", "to", "-"]

mytext = open(sys.argv[1]).read()

results = Counter(mytext.replace(',','').replace('.','').lower().split()).most_common()

for word in results:
    if (word[0] not in ignore):
        if (word[1] > 1):
            print("{:15}{:3}".format(word[0], word[1]))
