#!/usr/bin/env python3

# ---------------------------------------------------------------------------
#
# mincomp, a compile tool for the minuscript format 
#
# ---------------------------------------------------------------------------
"""
Copyright (c) 2016, David H. Rogers 
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""
# ---------------------------------------------------------------------------

import argparse
import configparser
import json
import os
import sys
import textwrap

APP_version  = "1.0"
APP_input    = "products.json"

# ---------------------------------------------------------------------------
#
# get the type of output requested, from the file extension 
#
# ---------------------------------------------------------------------------

def get_output_type( outfile ):
    ftype = "none"
    extension = os.path.splitext(outfile)
    if (len(extension) == 2):
        ftype = extension[1].split(".")[1]
    return ftype

def get_file_basename( fname ):
    extension = os.path.splitext(fname)
    return extension[0]

def get_products( fname ):
    products = [] 
    if os.path.isfile(fname):
        with open( fname ) as products_file:
            products_data = json.load( products_file )
            for p in products_data["outputs"]:
                products.append(p["name"])
    else:
        print("ERROR: can't find expected file: " + APP_input)

    return products

# ---------------------------------------------------------------------------
#
# get initial settings from settings file, if there is one
#
# ---------------------------------------------------------------------------
conf_parser = argparse.ArgumentParser(
    # Turn off help, so we print all options in response to -h
    add_help=False
    )

args, remaining_argv = conf_parser.parse_known_args()

# ---------------------------------------------------------------------------
#
# command line options
#
# ---------------------------------------------------------------------------
# Don't surpress add_help here so it will handle -h
parser = argparse.ArgumentParser(
    # Don't mess with format of description
    formatter_class=argparse.RawDescriptionHelpFormatter,
    # Inherit options from config_parser
    parents=[conf_parser],
    # print script description with -h/--help
    epilog=textwrap.dedent('''\
        examples:
        
          mcompile 
            print the list of products that can be compiled.

          mcompile <product> 
            look in the local products.json file, and compile
            product <product> if it exists. If it doesn't exist,
            exit and report list of possible products.

            ''')
)
# parser.set_defaults(**defaults)
parser.add_argument( "-d", "--debug", action="store_true", default=False,
    help="run in debug mode: create all files, but do not clean up after pdf is created.")
parser.add_argument( "-v", "--verbose", action="store_true", default=False,
    help="report verbosely")
parser.add_argument( "-V", "--version", action="store_true", default=False,
    help="print version and exit")
parser.add_argument( "product", nargs="?", default="none", 
    help="name of products to compile" )

args = parser.parse_args(remaining_argv)

# do the work
notFound = True

# print version
if (args.version == True):
    print(APP_version)
    exit(0)

# print the list of products
if (args.product == "none"):
    for p in get_products(APP_input):
        print(p)
    exit(0)

if not os.path.isfile(APP_input):
    print("ERROR: can't find expected file: " + APP_input)
    exit(0)

with open( APP_input ) as products_file:
    products_data = json.load( products_file )

for p in products_data["outputs"]:

    if (p["name"] == args.product):
        # required
        command = "minuscript --manuscriptfile " + p["manuscriptfile"] + " --author " + p["authorfile"] 

        # optional

        # files
        # ---------------------------------------------------------
        if "output" in p:
            extension = get_output_type(p["output"])
            if (extension == "pdf"):
                command += " --manuscriptname " + get_file_basename(p["output"])
            else:
                print("ERROR: unsupported output type: " + extension) 
                exit(1)

        if "quotesfile" in p:
            command += " --quotesfile " + p["quotesfile"]

        if "synopsisfile" in p:
            command += " --synopsisfile " + p["synopsisfile"]

        # args that require decisions
        # ---------------------------------------------------------
        if "notetype" in p:
            if p["notetype"] == "endnotes":
                command += " --endnotes"
            elif p["notetype"] == "footnotes":
                command += " --footnotes"
            else:
                print("ERROR: invalid note type: " + p["notetype"])

        if "fontfamily" in p:
            if p["fontfamily"] == "courier":
                command += " --fontfamily pcr"
            elif p["fontfamily"] == "times":
                command += " --fontfamily ptr"
                print("NOTE: check font family")
            else:
                print("ERROR: invalid fontfamily: " + p["fontfamily"])

        # switches
        # ---------------------------------------------------------
        if "chapsum" in p:
            if (p["chapsum"] == "true"):
                command += " --chapsum"

        if "includedate" in p:
            if (p["includedate"] == "true"):
                command += " --includedate"

        if "filescenesep" in p:
            if (p["filescenesep"] == "true"):
                command += " --filescenesep"

        if "toc" in p:
            if (p["toc"] == "true"):
                command += " --toc"

        if "quotes" in p:
            if (p["quotes"] == "true"):
                command += " --quotes"

        if "synopsis" in p:
            if (p["synopsis"] == "true"):
                command += " --synopsis"

        if "tags" in p:
            command += " --tags " + p["tags"]

        if "underline" in p:
            if (p["underline"] == "true"):
                command += " --underline"

        if "wordcount" in p:
            if (p["wordcount"] == "true"):
                command += " --wordcount"

        notFound = False

        # execute the command
        print(command)
        os.system(command)

if (notFound):
    print("ERROR: product \"" + args.product + "\" not found. Valid products:")
    for p in get_products(APP_input):
        print("    " + p)
